{
 "title": "WhatsApp Demo",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Channels Creations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(channels_creations)", "legendFormat": "channels creations" }
   ]
  },
  {
   "title": "Channels Creations - by channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(channels_creations) by (channel)",
     "legendFormat": "{{ channel }}"
    }
   ]
  },
  {
   "title": "Contacts Messages",
   "type": "graph",
   "description": "Total Messages sent by contact without count token activation message.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(contacts_messages)", "legendFormat": "Contact Messages" }
   ]
  },
  {
   "title": "Contacts Messages - by Channel",
   "type": "graph",
   "description": "Total Messages sent by contact without count token activation message.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(contacts_messages) by (channel)",
     "legendFormat": "{{ channel }}"
    }
   ]
  },
  {
   "title": "Contacts Activations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(contacts_activations)", "legendFormat": "Contact Activation" }
   ]
  },
  {
   "title": "Contacts Activations - by Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(contacts_activations) by (channel)",
     "legendFormat": "{{ channel }}"
    }
   ]
  },
  {
   "title": "Contacts Activated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(contacts_activated)", "legendFormat": "contacts activated" }
   ]
  },
  {
   "title": "Contacts Activated - by Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(contacts_activated) by (channel)",
     "legendFormat": "{{ channel }}"
    }
   ]
  }
 ]
}